[pytest]
bdd_features_base_dir = features
testpaths = features
python_files = test_*.py
addopts = -v --tb=short --alluredir=allure-results
markers =
    smoke: pruebas rápidas de humo
    login: escenarios de inicio de sesión
    cart: escenarios de carrito
    checkout: flujo de compra end-to-end
